import { app } from 'electron'
import {
  autoUpdater,
  type ProgressInfo,
  type UpdateCheckResult as ElectronUpdateCheckResult
} from 'electron-updater'

// Public API re-exports: these names were exported by this module before the
// electron-updater integration and are preserved so existing imports keep
// working. The canonical implementations still live in their own modules.
export { compareVersions } from './versionCompare'
export type { UpdateManifest } from './updateManifest'

/**
 * Update service backed by electron-updater.
 *
 * The update feed is GitHub Releases: electron-updater resolves the latest
 * release, downloads its `latest.yml`, and uses that as the update manifest.
 * Checks never download (autoDownload is off) so the renderer can show the
 * Update Available dialog first; the download only starts on an explicit
 * `downloadUpdate()` call and installs silently via `quitAndInstall()`.
 */

/** Structured result returned by checkForUpdates(). Never throws. */
export interface UpdateCheckResult {
  currentVersion: string
  latestVersion: string
  updateAvailable: boolean
  forceUpdate: boolean
  minimumSupportedVersion: string | null
  releaseNotes: string[] | null
  /** Direct installer URL from the manifest, or '' when not published yet. */
  downloadUrl: string
  /** Non-null when the check failed (server unreachable, bad response, bad manifest). */
  error: string | null
}

// Configure the singleton updater once. autoDownload stays off so the dialog
// can be shown before any bytes are fetched; autoInstallOnAppQuit stays on so
// a downloaded-but-not-yet-installed update installs on a later normal quit
// (Discord / VS Code style).
autoUpdater.autoDownload = false
autoUpdater.autoInstallOnAppQuit = true
autoUpdater.logger = console
// electron-updater skips checks in unpackaged builds unless the dev config is
// forced, so enable it only in dev. Packaged builds keep the signed
// app-update.yml generated by electron-builder.
if (!app.isPackaged) {
  autoUpdater.forceDevUpdateConfig = true
}
// GitHub Releases provider. This makes electron-updater read the latest.yml
// attached to the newest GitHub release automatically.
autoUpdater.setFeedURL({
  provider: 'github',
  owner: 'Ujjalcha1',
  repo: 'nova-fetch',
  private: false
})

function toMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err)
}

/** A single release note entry as written to latest.yml by electron-builder. */
interface ReleaseNoteEntry {
  version: string
  note: string | null
}

/** Normalize electron-updater's releaseNotes into a bullet-able list. */
function normalizeReleaseNotes(
  notes: string | ReleaseNoteEntry[] | null | undefined
): string[] | null {
  if (Array.isArray(notes)) {
    const lines = notes
      .map((entry) => entry.note)
      .filter((note) => note != null && note.trim().length > 0) as string[]
    return lines.length > 0 ? lines : null
  }
  if (typeof notes !== 'string' || notes.trim() === '') return null
  return notes
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
}

export class UpdateService {
  /** The version of the currently installed application, read from Electron. */
  getCurrentVersion(): string {
    return app.getVersion()
  }

  /**
   * Ask electron-updater to check GitHub Releases for a newer version and
   * return a structured result. Never throws: network failures and malformed
   * feeds are reported through the `error` field instead.
   */
  async checkForUpdates(): Promise<UpdateCheckResult> {
    const currentVersion = this.getCurrentVersion()

    const failed = (error: string): UpdateCheckResult => ({
      currentVersion,
      latestVersion: '',
      updateAvailable: false,
      forceUpdate: false,
      minimumSupportedVersion: null,
      releaseNotes: null,
      downloadUrl: '',
      error
    })

    let result: ElectronUpdateCheckResult | null
    try {
      result = await autoUpdater.checkForUpdates()
    } catch (err) {
      return failed(`Update server unreachable: ${toMessage(err)}`)
    }

    if (!result) {
      return failed('Update check is unavailable in this environment')
    }

    const updateInfo = result.updateInfo
    return {
      currentVersion,
      latestVersion: updateInfo.version,
      updateAvailable: result.isUpdateAvailable,
      // electron-updater has no forced-update concept; updates are optional.
      forceUpdate: false,
      minimumSupportedVersion: null,
      releaseNotes: normalizeReleaseNotes(updateInfo.releaseNotes),
      downloadUrl: '',
      error: null
    }
  }

  /**
   * Download the pending update using electron-updater. Resolves once the
   * download is complete and verified. Progress is streamed on the
   * `download-progress` event (see onDownloadProgress).
   */
  async downloadUpdate(): Promise<void> {
    await autoUpdater.downloadUpdate()
  }

  /**
   * Install the downloaded update and quit NovaFetch. Runs the NSIS installer
   * silently (/S) and relaunches the app afterwards, so the installer wizard
   * never appears.
   */
  quitAndInstall(silent = true, runAfterInstall = true): void {
    autoUpdater.quitAndInstall(silent, runAfterInstall)
  }

  /** Subscribe to download progress. Returns an unsubscribe function. */
  onDownloadProgress(callback: (progress: ProgressInfo) => void): () => void {
    autoUpdater.on('download-progress', callback)
    return () => {
      autoUpdater.removeListener('download-progress', callback)
    }
  }
}

/** Singleton instance for app-wide use. */
export const updateService = new UpdateService()
